Update gh-actions-core.yml

diff --git a/.github/workflows/gh-actions-core.yml b/.github/workflows/gh-actions-core.yml
--- a/.github/workflows/gh-actions-core.yml
+++ b/.github/workflows/gh-actions-core.yml
@@ -15,7 +15,9 @@ jobs:
             - uses: actions/checkout@v4
             - name: check is NG
               if: env.target == ''
-              run: exit 1
+              run: |
+                echo '::error title=secrets.DISCORD_ACCESS_TOKEN is NG::secrets.DISCORD_ACCESS_TOKEN is NG'
+                exit 1
 
     build:
         runs-on: ubuntu-latest
